[workspace]
members = [
	"api",
	"database",
	"minecraft",
	"api/macros",
	"translate",
]

[package]
name = "statpixel"
version = "0.1.4"
edition = "2021"
license = "GPL-3.0"
authors = ["Matthew Polak <contact@matteopolak.com>"]
repository = "https://github.com/matteopolak/statpixel"
readme = "https://github.com/matteopolak/statpixel/blob/main/README.md"

[[bin]]
name = "statpixel"
path = "bin/main.rs"

[[bench]]
name = "bench_main"
harness = false

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
api = { path = "./api" }
bincode = "2.0.0-rc.3"
chrono = "0.4.24"
database = { path = "./database" }
dotenvy = "0.15.7"
flate2 = "1.0.26"
futures = "0.3.28"
fxhash = "0.2.1"
governor = "0.5.1"
minecraft = { path = "./minecraft" }
skia-safe = "0.62.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
translate = { path = "./translate" }

[dependencies.diesel]
version = "2.0.4"
features = ["uuid", "chrono"]

[dependencies.diesel-async]
version = "0.2.2"
features = ["postgres"]
# features = ["allow-non-simd"]

[dependencies.tokio]
version = "1.27.0"
features = ["macros", "rt-multi-thread"]

[dependencies.uuid]
version = "1.3.1"
features = ["serde"]

[dependencies.plotters]
git = "https://github.com/plotters-rs/plotters.git"
branch = "next-release-devel"

[dependencies.poise]
version = "0.5.5"
features = []

[dependencies.serenity]
version = "0.11.5"
default-features = false
features = ["rustls_backend", "chrono"]

[dev-dependencies]
criterion = "0.4.0"
serde_json = "1.0.96"
