[workspace]
members = [
	"api",
	"database",
	"minecraft",
	"api/macros",
	"translate",
]

[package]
name = "statpixel"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0"
authors = ["Matthew Polak <contact@matteopolak.com>"]

[[bin]]
name = "statpixel"
path = "src/main.rs"

[dependencies]
api = { path = "./api" }
database = { path = "./database" }
macros = { path = "./api/macros" }
minecraft = { path = "./minecraft" }
translate = { path = "./translate" }
skia-safe = "0.62.0"
poise = "0.5.5"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.7"
diesel = { version = "2.0.4", features = ["uuid", "chrono"] }
uuid = { version = "1.3.1", features = ["serde"] }
once_cell = "1.17.1"
thiserror = "1.0.40"
r2d2 = "0.8.10"
fluent = "0.16.0"
intl-memoizer = "0.5.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
futures = "0.3.28"
flate2 = "1.0.26"
bson = "2.6.1"
chrono = "0.4.24"
reqwest = "0.11.17"
governor = "0.5.1"
