[workspace]
members = [
	"api",
	"database",
	"minecraft",
	"api/macros",
	"translate",
]


[package]
name = "statpixel"
version = "0.1.4"
edition = "2021"
license = "GPL-3.0"
authors = ["Matthew Polak <contact@matteopolak.com>"]
repository = "https://github.com/matteopolak/statpixel"
readme = "https://github.com/matteopolak/statpixel/blob/main/README.md"

[[bin]]
name = "statpixel"
path = "bin/main.rs"

[[bench]]
name = "bench_main"
harness = false

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
api = { path = "./api" }
database = { path = "./database" }
minecraft = { path = "./minecraft" }
translate = { path = "./translate" }
poise = "0.5.5"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.7"
diesel = { version = "2.0.4", features = ["uuid", "chrono"] }
uuid = { version = "1.3.1", features = ["serde"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
futures = "0.3.28"
flate2 = "1.0.26"
chrono = "0.4.24"
governor = "0.5.1"
bincode = "2.0.0-rc.3"
fxhash = "0.2.1"
diesel-async = { version = "0.2.2", features = ["postgres"] }

[dev-dependencies]
criterion = "0.4.0"
