[workspace]
members = [
	"api",
	"canvas",
	"database",
	"minecraft",
]

[package]
name = "discord"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0"
authors = ["Matthew Polak <contact@matteopolak.com>"]

[dependencies]
api = { path = "./api" }
canvas = { path = "./canvas" }
database = { path = "./database" }
minecraft = { path = "./minecraft" }
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.7"
diesel = { version = "2.0.4", features = ["uuid"] }
uuid = { version = "1.3.1", features = ["serde"] }
once_cell = "1.17.1"
thiserror = "1.0.40"
r2d2 = "0.8.10"
poise = "0.5.5"
fluent = "0.16.0"
intl-memoizer = "0.5.1"
tracing = "0.1.38"
tracing-subscriber = "0.3.17"

[[bin]]
name = "statpixel"
path = "src/main.rs"
