[package]
name = "database"
version = "0.10.0"
edition = "2021"
license = "GPL-3.0"
authors = ["Matthew Polak <contact@matteopolak.com>"]

[dependencies]
chrono = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
uuid = { workspace = true }
