[package]
name = "database"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
chrono = "0.4.24"
diesel = { version = "2.0.4", features = ["postgres", "r2d2"] }
uuid = { version = "1.3.1", features = ["serde"] }
