[package]
name = "translate"
version = "0.1.4"
edition = "2021"
license = "GPL-3.0"
authors = ["Matthew Polak <contact@matteopolak.com>"]

[dependencies]
bincode = "2.0.0-rc.3"
chrono = { version = "0.4.24", features = ["unstable-locales"] }
database = { path = "../database" }
diesel = "2.0.4"
fluent = "0.16.0"
intl-memoizer = "0.5.1"
num-format = "0.4.4"
poise = "0.5.5"
r2d2 = "0.8.10"
reqwest = "0.11.17"
serde_json = "1.0.96"
thiserror = "1.0.40"
tracing = "0.1.37"
uuid = "1.3.2"

[dev-dependencies]
api = { path = "../api" }
