[package]
name = "minecraft"
version = "0.1.4"
edition = "2021"
license = "GPL-3.0"
authors = ["Matthew Polak <contact@matteopolak.com>"]

[dependencies]
bincode = "2.0.0-rc.3"
darling = "0.20.1"
konst = "0.3.4"
once_cell = "1.17.1"
proc-macro2 = "1.0.56"
quote = "1.0.26"
serde = { version = "1.0.160", features = ["derive"] }
skia-safe = { version = "0.62.0", features = ["textlayout"] }
thiserror = "1.0.40"
