[package]
name = "minecraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
konst = "0.3.4"
once_cell = "1.17.1"
serde = { version = "1.0.160", features = ["derive"] }
skia-safe = "0.62.0"
