[package]
name = "minecraft"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0"
authors = ["Matthew Polak <contact@matteopolak.com>"]

[dependencies]
konst = "0.3.4"
once_cell = "1.17.1"
serde = { version = "1.0.160", features = ["derive"] }
skia-safe = "0.62.0"
thiserror = "1.0.40"
