[package]
name = "api"
version = "0.1.4"
edition = "2021"
license = "GPL-3.0"
authors = ["Matthew Polak <contact@matteopolak.com>"]

[dependencies]
chrono = { version = "0.4.24", features = ["serde", "unstable-locales"] }
database = { path = "../database" }
diesel = "2.0.4"
diesel-async = "0.2.2"
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
futures = "0.3.28"
governor = "0.5.1"
macros = { path = "./macros" }
minecraft = { path = "../minecraft" }
moka = { version = "0.10.2", features = ["future"] }
num-format = "0.4.4"
once_cell = "1.17.1"
poise = "0.5.5"
pure-rust-locales = "0.5.6"
reqwest = "0.11.16"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
skia-safe = "0.62.0"
tracing = "0.1.37"
translate = { path = "../translate" }
uuid = { version = "1.3.1", features = ["v4", "serde"] }

[dev-dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros"] }
