[package]
name = "api"
version = "0.1.3"
edition = "2021"
license = "GPL-3.0"
authors = ["Matthew Polak <contact@matteopolak.com>"]

[dependencies]
governor = "0.5.1"
macros = { path = "./macros" }
minecraft = { path = "../minecraft" }
translate = { path = "../translate" }
moka = { version = "0.10.2", features = ["future"] }
once_cell = "1.17.1"
reqwest = "0.11.16"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.3.1", features = ["v4", "serde"] }
skia-safe = "0.62.0"
num-format = "0.4.4"
poise = "0.5.5"
futures = "0.3.28"

[dev-dependencies]
dotenvy = "0.15.7"
