[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
http-cache-reqwest = { version = "0.9.0", default-features = false, features = ["manager-moka"] }
moka = { version = "0.10.2", features = ["future"] }
once_cell = "1.17.1"
oneshot = "0.1.5"
reqwest = "0.11.16"
reqwest-middleware = "0.2.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.13", features = ["limit", "buffer", "util"] }
uuid = { version = "1.3.1", features = ["v4", "serde"] }

[dev-dependencies]
dotenvy = "0.15.7"
